name: Run Code on Push

on:
  push:
    branches:
      - annika/master  # Change to your desired branch

jobs:
  run-my-code:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # or whatever you need

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check working directory
        run: pwd && ls -al

      - name: Run integration.py with PYTHONPATH set
        run: |
          export PYTHONPATH=/home/runner/work/mdwarf-habitability/mdwarf-habitability
          python tests/integration.py